spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kiosk_db
    username: kiosk_user
    password: kiosk1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: true
      lifecycle-management: start-only

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: redis1234

#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
#      embedding:
#        options:
#          model: text-embedding-3-small
#    vectorstore:
#      redis:
#        uri: redis://:redis1234@localhost:6379
#        index: menu-index
#        prefix:
#        menu:

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.ai: debug